version: "3"

services:
  slack_translate: # flask周りの設定
    build: 
      context: ./flask
      dockerfile: Dockerfile
    command: uwsgi --socket :8081 --module app.wsgi --py-autoreload 1 --logto /tmp/docker.log --ini /code/app.ini
    volumes: # longのvolumesは自動でフォルダが作られることによるエラーの対策
      - ./flask:/code
#      - type: bind # volumesはbind mount 指定したフォルダとコンテナ内のフォルダが共有される
#        source: "./flask" # "共有元"
#        target: "/code" # "共有先"
      - socket:/tmp
    tty: true
    hostname: slack_translate
    container_name: slack_translate

  nginx:
    image: nginx:latest
    ports:
      - "8081:8081"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
#      - type: bind
#        source: "./nginx/nginx.conf"
#        target: /etc/nginx/conf.d/default.conf
      - socket:/tmp

volumes:
  socket: